# Generated by Django 5.0.3 on 2026-01-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_pic",
            field=models.URLField(blank=True, null=True),
        ),
    ]
