# Generated by Django 5.0.3 on 2026-01-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account_app", "0002_customuser_user_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_pic",
            field=models.ImageField(blank=True, null=True, upload_to="user_photo/"),
        ),
    ]
