# Generated by Django 5.0.3 on 2025-12-28 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_name", models.CharField(blank=True, max_length=25, null=True)),
                ("artist_bio", models.TextField(blank=True)),
                (
                    "artist_image",
                    models.FileField(blank=True, upload_to="artist_image/"),
                ),
                ("country", models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_name", models.CharField(default="melody", max_length=20)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Songs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("duration", models.DurationField()),
                ("release_date", models.DateTimeField(blank=True)),
                (
                    "songs_file",
                    models.FileField(
                        upload_to="songs/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3"]
                            )
                        ],
                    ),
                ),
                ("cover_image", models.ImageField(upload_to="music_image/")),
                ("lyrics", models.TextField(blank=True)),
                ("language", models.CharField(max_length=20)),
                (
                    "views",
                    models.PositiveBigIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "likes_count",
                    models.PositiveBigIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "artist",
                    models.ManyToManyField(
                        related_name="songs_artist", to="songs_app.artist"
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        related_name="songs_genre", to="songs_app.genre"
                    ),
                ),
            ],
        ),
    ]
