# Generated by Django 5.0.3 on 2025-12-31 08:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "songs_app",
            "0002_album_songs_album_listen_history_song_play_playback_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="listen_history_song_play_playback",
            unique_together={("user", "song")},
        ),
    ]
