# Generated by Django 5.0.3 on 2026-01-01 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0003_alter_listen_history_song_play_playback_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="listen_history_song_play_playback",
            unique_together=set(),
        ),
    ]
