# Generated by Django 5.0.3 on 2026-01-01 03:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0004_alter_listen_history_song_play_playback_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="listen_history_song_play_playback",
            unique_together={("user", "song")},
        ),
    ]
