# Generated by Django 5.0.3 on 2026-01-01 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0005_alter_listen_history_song_play_playback_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="listen_history_song_play_playback",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="listen_history_song_play_playback",
            name="count",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listen_history_song_play_playback",
            name="days",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="listen_history_song_play_playback",
            unique_together={("user", "song", "days")},
        ),
    ]
