# Generated by Django 5.0.3 on 2026-01-19 07:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "songs_app",
            "0006_alter_listen_history_song_play_playback_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="video_song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="video_song/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "mkv", "webm"]
                            )
                        ],
                    ),
                ),
                (
                    "song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_song",
                        to="songs_app.songs",
                    ),
                ),
            ],
        ),
    ]
