# Generated by Django 5.0.3 on 2026-02-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0007_video_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="playlist_cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="playlist_cover_image/"
            ),
        ),
    ]
