# Generated by Django 5.0.3 on 2026-02-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0008_playlist_playlist_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listen_history_song_play_playback",
            name="days",
            field=models.DateField(null=True),
        ),
    ]
