# Generated by Django 5.0.3 on 2026-02-28 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0009_alter_listen_history_song_play_playback_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_file", models.FileField(upload_to="songs/source/")),
                ("file_size", models.BigIntegerField()),
                ("checksum", models.CharField(max_length=128)),
                ("storage_provider", models.CharField(default="local", max_length=50)),
                (
                    "processing_status",
                    models.CharField(default="pending", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_asset",
                        to="songs_app.songs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hls_master_url", models.URLField()),
                ("hls_bit_64", models.URLField(blank=True, null=True)),
                ("hls_bit_128", models.URLField(blank=True, null=True)),
                ("hls_bit_256", models.URLField(blank=True, null=True)),
                ("is_drm_enabled", models.BooleanField(default=False)),
                ("storage_provider", models.CharField(default="local", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream",
                        to="songs_app.songs",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="video_song",
        ),
    ]
