# Generated by Django 5.0.3 on 2026-02-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0011_video_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="checksum",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
