# Generated by Django 5.0.3 on 2026-03-01 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0012_alter_mediaasset_checksum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songs",
            name="songs_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="songs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3"]
                    )
                ],
            ),
        ),
    ]
