# Generated by Django 5.0.3 on 2026-03-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0013_alter_songs_songs_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediaasset",
            name="file_size",
        ),
    ]
