# Generated by Django 5.0.3 on 2026-06-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0014_remove_mediaasset_file_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="songs",
            name="songs_file",
        ),
    ]
