# Generated by Django 5.0.3 on 2026-06-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0015_remove_songs_songs_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songs",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="music_image/"),
        ),
        migrations.AlterField(
            model_name="songs",
            name="release_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
