# Generated by Django 5.0.3 on 2026-06-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0016_alter_songs_cover_image_alter_songs_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songs",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
