# Generated by Django 5.0.3 on 2026-06-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0017_alter_songs_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songs",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
