# Generated by Django 5.0.3 on 2026-06-16 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0018_alter_songs_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songs",
            name="duration",
            field=models.DurationField(
                blank=True, default=datetime.timedelta(0), null=True
            ),
        ),
    ]
