# Generated by Django 5.0.3 on 2026-06-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs_app", "0019_alter_songs_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="albums/"),
        ),
    ]
